/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoo;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jose manuel
 */
public class addCuidados extends javax.swing.JFrame {
 
    ArrayList <animales> animal;
    /**
     * Creates new form addCuidadores
     */
    public addCuidados() {
        initComponents();
        animal = new ArrayList<animales>();
        rellenaAnimales();
        
    }
    public void rellenaAnimales(){
        try{
            FileInputStream file = new FileInputStream("animales.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            boolean finalFichero = false;
            while(!finalFichero){
                try{
                    animal.add((animales)inputFile.readObject());
                }catch(EOFException e){
                    finalFichero = true;
                }catch(Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        }catch(IOException f){
            JOptionPane.showMessageDialog(null, f.getMessage());
        }
    }
    
    public void saveCare(){
        try{
            FileOutputStream file= new FileOutputStream("animales.dat");
            ObjectOutputStream OutputFile = new ObjectOutputStream(file);
            for(int i=0; i < animal.size() ; i++){
                OutputFile.writeObject(animal.get(i));
            }
            OutputFile.close();
            JOptionPane.showMessageDialog(null, "Se ha guardado correctamente");
            this.dispose();
    }   catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capa0 = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        textNumCuidado = new javax.swing.JTextField();
        Lnombre1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        LApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        Lnombre3 = new javax.swing.JLabel();
        BoxEspecialidad = new javax.swing.JComboBox<>();
        jguardar = new javax.swing.JButton();
        LApellido1 = new javax.swing.JLabel();
        textApellido1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(102, 255, 204));
        capa0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("añadir cuidador");
        jTitulo.setToolTipText("");
        capa0.add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 120));

        Lnombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Lnombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lnombre.setText("especialidad");
        capa0.add(Lnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 40));
        capa0.add(textNumCuidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 590, 40));

        Lnombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Lnombre1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lnombre1.setText("tipo clima");
        capa0.add(Lnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        capa0.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 590, 40));

        LApellido.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        LApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LApellido.setText("habitad");
        capa0.add(LApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 40));
        capa0.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 590, 40));

        Lnombre3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Lnombre3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lnombre3.setText("numero cuidador");
        Lnombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Lnombre3KeyTyped(evt);
            }
        });
        capa0.add(Lnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 40));

        BoxEspecialidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        capa0.add(BoxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 190, 40));

        jguardar.setText("añadir");
        capa0.add(jguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        LApellido1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        LApellido1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LApellido1.setText("habitad");
        capa0.add(LApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, 40));
        capa0.add(textApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 590, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void Lnombre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Lnombre3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Lnombre3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCuidados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxEspecialidad;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LApellido1;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Lnombre1;
    private javax.swing.JLabel Lnombre3;
    private javax.swing.JPanel capa0;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JButton jguardar;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textApellido1;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumCuidado;
    // End of variables declaration//GEN-END:variables
}
