/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoo;

/**
 *
 * @author jose manuel
 */
public class addEspecialidad extends javax.swing.JFrame {

    /**
     * Creates new form addCuidadores
     */
    public addEspecialidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capa0 = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        textNumCuidado = new javax.swing.JTextField();
        Lnombre1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        LApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        Lnombre3 = new javax.swing.JLabel();
        jguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(102, 255, 204));
        capa0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("añadir especialidad");
        jTitulo.setToolTipText("");
        capa0.add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 120));
        capa0.add(textNumCuidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 590, 40));

        Lnombre1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Lnombre1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lnombre1.setText("Nombre especialidad");
        capa0.add(Lnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 30));

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        capa0.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 590, 40));

        LApellido.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        LApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LApellido.setText("salario medio");
        capa0.add(LApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));
        capa0.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 590, 40));

        Lnombre3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Lnombre3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lnombre3.setText("Extra por especialidad");
        Lnombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Lnombre3KeyTyped(evt);
            }
        });
        capa0.add(Lnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 40));

        jguardar.setText("añadir");
        capa0.add(jguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void Lnombre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Lnombre3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Lnombre3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEspecialidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel Lnombre1;
    private javax.swing.JLabel Lnombre3;
    private javax.swing.JPanel capa0;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JButton jguardar;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumCuidado;
    // End of variables declaration//GEN-END:variables
}
